### ISSUE TITLE
Read files as UTF-8, regardless of locale

### ISSUE THREAD

**Issue by judah** [dhall-lang/dhall-haskell#504]
Currently, Dhall changes the encoding that it expects of input files based on the current locale.  My understanding from the docs, and from #188, is that the input is expected to be UTF-8.  So there are a few places in the code that probably need to be changed.

One place in particular:
https://github.com/dhall-lang/dhall-haskell/blob/5416269d5f99e8986294d0a7d7a124726cfb450e/src/Dhall/Import.hs#L459

The behavior of `Data.Text.IO.readFile` depends on the value of the user's locale (for example, `$LANG`): http://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text-IO.html#g:2

**Comment by Profpatsch** [comment]
We already fixed some of the imports a few months back iirc, might have missed a few spots.

**Comment by Gabriel439** [comment]
Yes, the standard requires that the character encoding is UTF-8 (See: https://github.com/dhall-lang/dhall-lang/blob/master/standard/dhall.abnf#L3), so I'll fix these

**Comment by Gabriel439** [comment]
Actually, I wonder if using `System.IO.setLocaleEnding` would fix this globally so that we don't have to set it for every `Handle`:

http://hackage.haskell.org/package/base-4.11.1.0/docs/GHC-IO-Encoding.html#v:setLocaleEncoding

**Comment by Gabriel439** [comment]
@judah: Could you try out #506 to see if that works for you?

**Comment by mrkkrp** [comment]
I've tried #506 but it does not solve the issue. Maybe it's because the code is read at compile time with `staticDhallExpression`? Still getting:

> hGetContents: invalid argument (invalid byte sequence)

(Only when the file contains Unicode, of course.)

**Comment by Gabriel439** [comment]
@mrkkrp: I just added another commit to that pull request to also set the locale for `staticDhallExpression`.  Could you give that a try and see if it fixes the issue for you?

**Comment by Gabriel439** [comment]
I will go ahead and merge #506 since it seems like an improvement anyway, but I'll keep this issue open until I hear confirmation that this is fixed

**Comment by mrkkrp** [comment]
We have worked around this by setting `LANG` and `LOCALE_ARCHIVE` on GHC invocations (it's invoked by Bazel in a controlled environment). I may have time to test this fix also next week.

**Comment by ocharles** [comment]
@mrkkrp are you able to give this another test?

**Comment by mrkkrp** [comment]
No, I'm not working on that project anymore and don't have access to the code base :)

**Comment by ocharles** [comment]
No problem! Do you recall which locale you were using when the problem happened?

@judah would you be able to re-test?

**Comment by judah** [comment]
Pinging: @thumphries @nhibberd

**Comment by judah** [comment]
I do recall the LANG variable was unset, so that the default encoding was effectively ASCII.  (Like mrkkrp, I'm also unable to test this fix.)

**Comment by thumphries** [comment]
Yeah feel free to close, we will know for sure in a couple of days but the changes look sufficient to me.
